name: Dynamic Repo Pins

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Generate pinned repos section
        run: |
          echo "<!--START_PROJECT_SECTION-->" > PINS.md
          echo "## 🚀 My Projects" >> PINS.md
          GH_USER="Sanskriti10247"
          repos=$(curl -s "https://api.github.com/users/$GH_USER/repos?per_page=100&sort=updated" | jq -r '.[] | select(.archived==false) | [.name, .html_url] | @tsv')
          while IFS=$'\t' read -r name url; do
            echo "[![](https://github-readme-stats.vercel.app/api/pin/?username=$GH_USER&repo=$name&theme=radical&title_color=F718C2&text_color=ffffff&bg_color=0d1117)]($url)" >> PINS.md
          done <<< "$repos"
          echo "<!--END_PROJECT_SECTION-->" >> PINS.md

      - name: Merge into README
        run: |
          awk '/<!--START_PROJECT_SECTION-->/ {show=1; print; while (getline < "PINS.md") print; next} /<!--END_PROJECT_SECTION-->/ {show=0} !show' README.md > TEMP.md
          mv TEMP.md README.md

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update project pins" || echo "No changes"
          git push
